#!/bin/bash
#
# This UNINSTALL script is meant to install Informtest VISA
# onto a Linux system (GNU/Debian).
#
#  Copyright 2017,
#  Holding Informtest Corporation.
#  All Rights reserved.


sFail=1
sOk=0

inst_prefix="/usr/local/vxipnp/linux"
link_prefix="/usr"

remove_link() {
	filename=$1
	rm -f "$link_prefix/$2/$filename"
}

# Verify root user
if [ $EUID -ne 0 ]; then
	echo "This script must be run as root."
	echo "Installation is aborted."
	exit $sFail
fi

remove_link "InfNetTest" local/bin

# Remove QtVisaConfig shortcut from the current desktop
rm -f /home/$SUDO_USER/Desktop/InfNetTest.desktop
